---
- name: Install roundcube package
  apt:
    name: "{{ roundcube_package }}"
    state: "{{ roundcube_package_state }}"
    update_cache: yes

- name: Deploy roundcube config template
  template:
    src: templates/config.inc.php.j2
    dest: /var/www/roundcube/config/config.inc.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Link logs to a sane location
  file:
    src: '/var/www/roundcube/logs'
    dest: '/var/log/roundcube'
    owner: www-data
    group: www-data
    state: link
